package com.chuckfarah.streaminghistory.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme color primitives
val md_theme_light_primary = Color(0xFFD4891A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE4B0)
val md_theme_light_onPrimaryContainer = Color(0xFF3C2300)
val md_theme_light_secondary = Color(0xFF5A6A78)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEE2E7)
val md_theme_light_onSecondaryContainer = Color(0xFF1A2026)
val md_theme_light_tertiary = Color(0xFF8F6A3E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE3C2)
val md_theme_light_onTertiaryContainer = Color(0xFF2B1A0A)
val md_theme_light_error = Color(0xFFC62828)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFCDD2)
val md_theme_light_onErrorContainer = Color(0xFFB71C1C)
val md_theme_light_background = Color(0xFFF7F5F2)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFF0EBE6)
val md_theme_light_onSurfaceVariant = Color(0xFF5E5C5A)
val md_theme_light_outline = Color(0xFF7C756E)
val md_theme_light_inverseOnSurface = Color(0xFFF5F5F5)
val md_theme_light_inverseSurface = Color(0xFF1C1B1F)

// Dark theme color primitives
val md_theme_dark_primary = Color(0xFFF5B041)
val md_theme_dark_onPrimary = Color(0xFF121212)
val md_theme_dark_primaryContainer = Color(0xFF6E4C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE4B0)
val md_theme_dark_secondary = Color(0xFF7D8C9B)
val md_theme_dark_onSecondary = Color(0xFF121212)
val md_theme_dark_secondaryContainer = Color(0xFF2E3841)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6DFE8)
val md_theme_dark_tertiary = Color(0xFFC49A6C)
val md_theme_dark_onTertiary = Color(0xFF121212)
val md_theme_dark_tertiaryContainer = Color(0xFF4D3520)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE3C2)
val md_theme_dark_error = Color(0xFFE57373)
val md_theme_dark_onError = Color(0xFF121212)
val md_theme_dark_errorContainer = Color(0xFF2D1B1B)
val md_theme_dark_onErrorContainer = Color(0xFFFFCDD2)
val md_theme_dark_background = Color(0xFF0D0F12)
val md_theme_dark_onBackground = Color(0xFFE6E1DB)
val md_theme_dark_surface = Color(0xFF161A1F)
val md_theme_dark_onSurface = Color(0xFFE6E1DB)
val md_theme_dark_surfaceVariant = Color(0xFF1E2329)
val md_theme_dark_onSurfaceVariant = Color(0xFF9DA4AB)
val md_theme_dark_outline = Color(0xFF6C7A89)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1DB)

// Extended semantic colors (success and warning), not part of Material 3 ColorScheme
val success_light = Color(0xFF2E7D32)
val onSuccess_light = Color(0xFFFFFFFF)
val successContainer_light = Color(0xFFC8E6C9)
val onSuccessContainer_light = Color(0xFF1B5E20)

val warning_light = Color(0xFFF9A825)
val onWarning_light = Color(0xFF121212)
val warningContainer_light = Color(0xFFFFF9C4)
val onWarningContainer_light = Color(0xFF5D4037)

val success_dark = Color(0xFF66BB6A)
val onSuccess_dark = Color(0xFF121212)
val successContainer_dark = Color(0xFF1B3C1E)
val onSuccessContainer_dark = Color(0xFFA5D6A7)

val warning_dark = Color(0xFFFBC02D)
val onWarning_dark = Color(0xFF121212)
val warningContainer_dark = Color(0xFF3B2E00)
val onWarningContainer_dark = Color(0xFFFFF176)
